auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Xiaokai.wang blog
url: http://xiaokai-wang.github.io
feed: /atom.xml
author_info: <a href="http://xiaokai-wang.github.io/">Xiaokai.wang</a>

comments :

provider : disqus

disqus :

short_name : xiaokai.wang
